# Generated by Django 3.2.7 on 2021-09-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0002_auto_20210905_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorMessage',
        ),
    ]
